name: PixelgamesJail
main: Authors\PixelgamesJail\Jail
api: [3.0.0, 4.0.0]
version: 1.0#
author: hoyinm14mc, iStrafeNubzHDyt
description: Ein erweitertes Gefängnis-Bestrafungssystem für PocketMine-MP-Server
load: POSTWORLD

commands:
  deljail:
    description: Entfernt ein Gefängnis
    permission: jail.command.deljail
    usage: /deljail <Gefängnisname>

  setjail:
    description: Setzt ein Gefängnis
    permission: jail.command.setjail
    usage: /setjail <Gefängnisname> [args...]
    aliases: ["jailset"]

  jails:
    description: Zeigt eine Liste aller verfügbaren Gefängnisse
    permission: jail.command.jails
    usage: /jails
    aliases: ["jaillist"]

  jail:
    description: Sperrt einen Spieler ein
    permission: jail.command.jail
    usage: /jail <Spieler> <Gefängnisname> <Zeit in Min.|-i> <Grund..>

  unjail:
    description: Befreit einen Spieler, der online oder offline ist
    permission: jail.command.unjail
    usage: /unjail <Spieler>

  jailed:
    description: Zeigt einer Liste aller Gefangenen
    permission: jail.command.jailed
    usage: /jailed
    aliases: ["prisoners"]

  switchjail:
    description: Verlegt einen Gefangenen in ein anderes Gefängnis
    permission: jail.command.switchjail
    usage: /switchjail <Spieler> <Gefängnisname>
    aliases: ["transferjail", "jailswitch"]

  tpjail:
    description: Teleportiert einen Spieler zu einem Gefängnis
    permission: jail.command.jailtp
    usage: /tpjail <Gefängnisname> <Spieler>
    aliases: ["jailtp"]

  bail:
    description: Kaufe dich für Geld aus dem Gefängnis frei
    permission: jail.command.bail
    usage: /bail

  votejail:
    description: Votet einen Spieler in Gefängnis
    permission: jail.command.votejail
    usage: /votejail <Spieler>
    aliases: ["jailvote"]

  jailmine:
    description: Einstellungen für Gefängnisminen
    permission: jail.command.jailmine
    usage: /jailmine <reset|set|remove|check> <Gefängnisname(mine)>

  jailsellhand:
    description: Verkaufe deine gefarmten Erze, um Geld zu erhalten
    permission: jail.command.jailsellhand
    usage: /jailsellhand

  jailresetmine:
    descripiton: Resete deine Gefängnismine
    permission: jail.command.jailresetmine
    usage: /jailresetmine

  jailinfo:
    description: Zeigt Informationen über ein Gefängnis
    permission: jail.command.jailinfo
    usage: /jailinfo <Gefängnisname>
    aliases: ["jailcheck"]

  prisonerinfo:
    description: Zeigt Informationen über einen Gefangenen
    permission: jail.command.prisonerinfo
    usage: /prisonerinfo <Spieler>

    
permission:
  jail.override.restrictions:
    default: false
    description: Erlaubt es inhaftierten Spielern, Einschränkungen zu ignorieren

  jail.command.setjail:
    default: op
    description: Das Recht, ein Gefängnis zu setzen

  jail.command.deljail:
    default: op
    description: Das Recht, ein Gefängnis zu entfernen

  jail.command.jails:
    default: op
    description: Das Recht, alle verfügbaren Gefängnisse aufzulisten

  jail.command.jail:
    default: op
    description: Das Recht, Spieler in ein Gefängnis zu sperren

  jail.command.unjail:
    default: op
    description: Das Recht, Gefangene, die online/offline sind, freizulassen

  jail.command.jailed:
    default: op
    description: Das Recht, alle Gefangenen aufzulisten

  jail.command.switchjail:
    default: op
    description: Das Recht, einen Gefangenen in ein anderes Gefängnis zu verlegen

  jail.command.jailtp:
    default: true
    description: Das Recht, ein Gefängnis besuchen zu können

  jail.command.bail:
    default: true
    description: Das Recht, sich aus dem Gefängnis freizukaufen

  jail.command.jailmine:
    default: op
    description: Das Recht, Gefängnisminen zu verwalten

  jail.command.votejail:
    default: true
    description: Das Recht, einen Spieler, der sich schlecht verhält, ins Gefängnis zu voten

  jail.uuidcheck.bypass:
    default: false
    description: Das Recht, den UUID-Check beim Login zu umgehen

  jail.sign.destroy:
    default: op
    description: Das Recht, Bail-Schilder zu entfernen

  jail.sign.create:
    default: op
    description: Das Recht, Bail-Schilder zu erstellen

  jail.sign.use:
    default: true
    description: Das Recht, sich durch ein Bail-Schild freizukaufen

  jail.modify.bypass:
    default: op
    description: Das Recht, Gefängnisse zu bebauen/modifizieren

  jail.command.jailsellhand:
    default: true
    description: Das Recht für Gefangene, ihre in der Gefängnismine gefarmten Erze für Geld zu verkaufen

  jail.command.jailresetmine:
    default: true
    description: Das Recht für Gefangene, ihre Gefängnismine zu reseten

  jail.command.jailinfo:
    default: op
    description: Das Recht, Infomationen über ein Gefängnis abzurufen

  jail.command.prisonerinfo:
    default: op
    description: Das Recht, Informationen über einen Gefangenen abzurufen

  jail.showInOutMessage:
    default: true
    description: Das Recht, für das Betreten/Verlassen eines Gefängnisses eine Meldung zu erhalten

  jail.visit.bypass:
    default: op
    description: Das Recht, jedes Gefängnis besuchen zu dürfen
