####### Config von PixelgamesJail #######

### Einschränkungen für Gefangene ###
allow-chat: true
allow-command: false
allow-block-break: false
allow-block-place: false
allow-item-drop: false

#Wenn auf false, schränkt es das VECTOR3-Movement des Spielers ein, nicht die ganze POSITION
allow-movement: true

allow-attack: false
disable-damage: true


### Spracheinstellungen ###
# Unterstützte Sprachen: en
default-lang: en


### Einstellungen ###

#Lässt die Zeit weiterlaufen, wenn der Gefangene offline ist
offline-time-counting: false

#Fügt eine zusätzliche Strafzeit hinzu, wenn der Gefangene versucht, das Gefängnis zu zerstören
enable-penalty: true

#Die Höhe der dann hinzugefügten Strafzeit
penalty-time: 10

#Erlaubt es Gefangenen, sich mit /bail freizukaufen
allow-bail: true

#Erlaubt es normalen Spielern, ein Gefängnis zu betreten (Besuche erlauben)
allow-visit: true

#Der Geldbetrag, den ein Gefangener jede Sekunde zahlen muss, um sich freizukaufen
bail-per-second: 100

#Erlaubt es, Operatoren einzusperren
op-can-be-jailed: true

#Aktiviert den Updater beim Server-start (Latest Version Tracker)
updater-startup-fetch: true

#Aktiviert den planmäßigen AutoUpdateChecker
scheduled-update-checker: true

#Anzahl der Minuten zwischen jeden AutoUpdateCheck (Ignorieren, falls scheduled-update-checker=false)
scheduled-update-checker-interval: 45

#Anzahl an Votes, damit ein Spieler eingesperrt wird
votes-to-jail-player: 4

#Zeigt den Gefangenen einen Timer
show-prisoner-timer: true

#Überprüft die UUID der Spieler beim Joinen (Gefangene Spieler könnten ihren Namen etc. ändern)
check-UUID: true

#Zeiteinheit (min|sec|hr)
time-unit: min

#ItemID des Blocks, mit dem die Mine gefüllt wird
block: 15

#ItemID des Items, das Gefangene verkaufen können, um Geld zu erhalten
#Der Wert entspricht dem Item, das gedroppt wird, wenn man einen Block in der Mine zerstört
item: 265

#Belohnung pro 20 Blöcke
money-per-block: 1


#UpdateCheck-Kanal
#   Kanäle:
#   'poggit': Versionen, die vom PocketMine-Team geprüft werden
#   'github': Versionen, die garantiert UP-TO-DATE sind
#   '*': Beide der oben genannten Kanäle werden verwendet (>Empfohlen<)
# ('poggit' oder 'github' oder '*' angeben)
update-checker-channel: '*'


### Version der Config ###
#Dies nicht bearbeiten, sonst funktioniert das Plugin möglicherweise nicht richtig
v: 1.2.1
